# Build Stage
FROM rust:latest AS build

WORKDIR /app

COPY . .

RUN cargo build --release

# Prod Stage
FROM rust:latest

WORKDIR /app

COPY --from=build /app/target/release/service2 .

CMD ["./service2"]

